# Generated by Django 4.2.7 on 2023-11-24 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='webprofile',
            name='email',
            field=models.EmailField(default=1, max_length=50, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webprofile',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='webprofile',
            name='username',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
