# Generated by Django 4.2.7 on 2023-11-28 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0002_webprofile_last_login_alter_webprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
