# Generated by Django 4.2.7 on 2023-11-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0003_alter_webprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebProfile',
        ),
    ]
