# Generated by Django 4.2.7 on 2024-04-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bytebazaaruserprofile",
            name="email",
        ),
    ]
