# Generated by Django 4.2.7 on 2023-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bytebazaaruserprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytebazaaruserprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
