# Generated by Django 4.2.7 on 2023-12-09 20:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bytebazaaruserprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytebazaaruserprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
