# Generated by Django 4.2.7 on 2024-04-04 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_token_alter_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
