# Generated by Django 4.2.7 on 2024-05-24 17:12

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Hadzhidimovo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='BG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Valentin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT', 'Credit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('DEBIT', 'Debit Card')], default='CREDIT', max_length=14),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(default='2932', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code.', regex='^[A-Za-z0-9 ]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='Kardzhaliev', max_length=30),
            preserve_default=False,
        ),
    ]
