# Generated by Django 4.2.7 on 2024-06-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
