# Generated by Django 4.2.7 on 2024-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cart_items_remove_cartitem_user_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
