# Generated by Django 4.2.7 on 2023-12-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_delete_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.product')),
                ('processor', models.CharField(max_length=50)),
                ('memory', models.IntegerField()),
                ('storage', models.IntegerField()),
            ],
            bases=('common.product',),
        ),
    ]
