# Generated by Django 4.2.7 on 2024-01-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='image',
        ),
    ]
