# Generated by Django 4.2.7 on 2023-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='graphics',
            field=models.CharField(default='RTX 3070', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.CharField(max_length=50),
        ),
    ]
