# Generated by Django 4.2.7 on 2024-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='cooler',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_card',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
