# Generated by Django 4.2.7 on 2023-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], default='computer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyboard',
            name='type',
            field=models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], default='keyboard', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='type',
            field=models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], default='monitor', max_length=20),
            preserve_default=False,
        ),
    ]
