# Generated by Django 4.2.7 on 2024-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_computer_cooler_computer_motherboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='adjustable_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='built_in_speakers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='curvature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='response_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cooler',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
