# Generated by Django 4.2.7 on 2023-12-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_computer'),
        ('catalog', '0002_computer_graphics_alter_computer_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.product')),
                ('resolution', models.CharField(max_length=20)),
                ('refresh_rate', models.CharField(max_length=10)),
                ('panel_type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=5)),
            ],
            bases=('common.product',),
        ),
    ]
