# Generated by Django 4.2.7 on 2023-12-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_computer'),
        ('catalog', '0003_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.product')),
                ('key_switch_type', models.CharField(choices=[('membrane', 'Membrane'), ('mechanical', 'Mechanical'), ('scissor', 'Scissor')], max_length=30)),
                ('backlight', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('wireless', models.BooleanField(default=False)),
            ],
            bases=('common.product',),
        ),
    ]
