# Generated by Django 4.2.7 on 2024-04-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_monitor_adjustable_stand_monitor_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='video_card',
        ),
    ]
