# Generated by Django 4.2.7 on 2024-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_computer_video_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the keyboard', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='format',
            field=models.CharField(choices=[('full_size', 'Full size'), ('tenkeyless', 'Tenkeyless (TKL)'), ('compact_75', 'Compact (75%)'), ('compact_65', 'Compact (65%)'), ('mini_60', 'Mini (60%)'), ('keypad', 'Keypad')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyboard',
            name='key_rollover',
            field=models.IntegerField(blank=True, help_text='Key rollover (N-key rollover)', null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='layout',
            field=models.CharField(choices=[('ansi', 'ANSI'), ('iso', 'ISO')], default='ansi', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='polling_rate_hz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Polling rate in Hz', max_digits=5, null=True),
        ),
    ]
