# Generated by Django 4.2.7 on 2024-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_computer_case_computer_cooling_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='cooling_solution',
            field=models.CharField(blank=True, choices=[('air', 'Air Cooling'), ('liquid', 'Liquid Cooling'), ('passive', 'Passive Cooling')], max_length=20, null=True),
        ),
    ]
