# Generated by Django 4.2.7 on 2024-04-09 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_computer_cooling_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dpi', models.IntegerField(help_text='Dots per inch (DPI)')),
                ('tracking_type', models.CharField(choices=[('optical', 'Optical'), ('laser', 'Laser'), ('trackball', 'Trackball')], max_length=30)),
                ('buttons', models.IntegerField(help_text='Number of buttons')),
                ('ergonomic', models.BooleanField(default=False)),
                ('wireless', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('polling_rate_hz', models.DecimalField(blank=True, decimal_places=2, help_text='Polling rate in Hz', max_digits=5, null=True)),
                ('brand', models.CharField(blank=True, help_text='Brand of the mouse', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
