# Generated by Django 4.2.7 on 2024-04-10 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_mouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('over_ear', 'Over-ear'), ('on_ear', 'On-ear'), ('in_ear', 'In-ear'), ('earbuds', 'Earbuds'), ('neckband', 'Neckband'), ('true_wireless', 'True wireless'), ('bone_conduction', 'Bone conduction'), ('open_back', 'Open-back'), ('closed_back', 'Closed-back')], max_length=20)),
                ('wireless', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, help_text='Brand of the headphones', max_length=100, null=True)),
                ('impedance_ohms', models.IntegerField(blank=True, help_text='Impedance in Ohms', null=True)),
                ('sensitivity_db', models.DecimalField(blank=True, decimal_places=2, help_text='Sensitivity in dB', max_digits=5, null=True)),
                ('frequency_response', models.CharField(blank=True, help_text='Frequency response range', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Color of the headphones', max_length=20, null=True)),
                ('noise_cancelling', models.BooleanField(default=False, help_text='Does it have noise-cancelling feature?')),
                ('microphone', models.BooleanField(default=False, help_text='Does it have a built-in microphone?')),
                ('foldable', models.BooleanField(default=False, help_text='Is it foldable for easy storage?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
