# Generated by Django 4.2.7 on 2024-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_headphones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='format',
            new_name='keyboard_format',
        ),
    ]
