# Generated by Django 4.2.7 on 2024-05-21 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_format_keyboard_keyboard_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=20)),
                ('battery_life', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('operating_system', models.CharField(blank=True, max_length=200, null=True)),
                ('touchscreen', models.BooleanField(default=False)),
                ('webcam', models.BooleanField(default=True)),
                ('fingerprint_reader', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
