# Generated by Django 4.2.7 on 2024-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphones',
            name='sensitivity_db',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sensitivity in dB', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='polling_rate_hz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Polling rate in Hz', max_digits=6, null=True),
        ),
    ]
