# Generated by Django 4.2.7 on 2024-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
