# Generated by Django 4.2.7 on 2023-12-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.product')),
                ('processor', models.CharField(max_length=50)),
                ('memory', models.IntegerField()),
                ('storage', models.IntegerField()),
            ],
        ),
    ]
