# Generated by Django 4.2.7 on 2023-12-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_computer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
